version: '2.2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.13.2
    environment:
      ELASTICSEARCH_HOSTS: http://localhost:9200
    volumes:
      - mbdata1:/usr/share/metricbeat/data
    depends_on:
      - elasticsearch

  metricbeat:
    image: docker.elastic.co/beats/heartbeat:7.13.2
    environment:
      ELASTICSEARCH_HOSTS: http://localhost:9200
    volumes:
      - hbdata1:/usr/share/heartbeat/data
    depends_on:
      - elasticsearch

volumes:
  esdata1:
    driver: local
  mbdata1:
    driver: local
  hbdata1:
    driver: local